name: "Build & Publish"
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-publish:
    name: rabbitmq${{ matrix.version }}-management
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [ '3.9', '3.10', '3.11' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Build and publish
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./rabbitmq${{ matrix.version }}.dockerfile
          push: true
          tags: ${{ secrets.DH_USERNAME }}/rabbitmq:${{ matrix.version }}-management-latest
